id: P010521
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22313
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་གཞུང་གསལ་བོར་བཤད་པ་ལེགས་བཤད་སྣང་བའི་གཏེར
  author: ''
  volumes:
    93a0a5599f504a03bf936b95364b98ea:
      image_group_id: I1KG1317
      title: ''
      volume_number: 1
      total_pages: 580
      base_file: v001.txt
