id: IDE3CED22
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T05:43:38+00:00'
last_modified: '2022-06-08T14:13:10.500356+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22313
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་གཞུང་གསལ་བོར་བཤད་པ་ལེགས་བཤད་སྣང་བའི་གཏེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ED11:
      image_group_id: I1KG1317
      title: ''
      total_pages: 580
      order: 1
      base_file: ED11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
